#!/usr/bin/env sh

# the layout for windows is bsp
yabai -m config layout bsp

# set the gap between the screen edge and windows
yabai -m config top_padding 6
yabai -m config bottom_padding 6
yabai -m config left_padding 6
yabai -m config right_padding 6
yabai -m config window_gap 6

# disable window shadow, requires SIP to be disabled
yabai -m config window_shadow off

# disable auto balancing of windows on change
yabai -m config auto_balance off

# size distribution for bsp splits, half and half
yabai -m config split_ratio 0.50

# focused windows have full opacity, while normal windows are slightly transparent
yabai -m config window_opacity on
yabai -m config active_window_opacity 1.0
yabai -m config window_opacity_duration 0.0
yabai -m config normal_window_opacity 0.90

# disable window transition animations
yabai -m config window_animation_duration 0.0

# set mouse interaction modifier key
yabai -m config mouse_modifier fn

# set modifier + left-click drag to move window
yabai -m config mouse_action1 move

# set modifier + right-click drag to resize window
yabai -m config mouse_action2 resize

# sketchybar integration: trigger updates on window focus and title change
yabai -m signal --add event=window_focused action="sketchybar -m --trigger window_focus &> /dev/null"
yabai -m signal --add event=window_title_changed action="sketchybar -m --trigger title_change &> /dev/null"

yabai -m rule --add app="^System Settings$" manage=off
